### ISSUE TITLE
Discard option for crypttab.

### ISSUE THREAD

**Issue by duckartes** [nbros652/LUKS-guided-manual-partitioning#1]
Ask if SSD to enable trim support, add discard option to crypttab.

**Comment by nbros652** [comment]
I don't have time right now to add this, but you're right! Hopefully, I'll be able to get to it in the next couple weeks. It should be noted that this needs to be enabled on the LVM and FS layers as well if it's going to be of any use in crypttab.
It should be noted that implementing TRIM is not advised on all SSDs. Some manufacturers explicitly state not to enable TRIM on their devices.

**Comment by duckartes** [comment]
Right on. I appreciate the script. I'm curious as to why Ubuntu doesn't
offer this out of the box?

**Comment by nbros652** [comment]
This is now implemented ... along with the warning that according to SSD manufacturers, some SSDs should have trim enabled and that trim may reveal information about encrypted data.

**Comment by duckartes** [comment]
Neat. I never thought about that. The deletion of data and persistence of others reveals "something?" 

I don't know the complexities of it. If you've got any reading for me, I'd appreciate it.

**Comment by nbros652** [comment]
Check out [this article](http://asalor.blogspot.com/2011/08/trim-dm-crypt-problems.html). It's a good, detailed write-up that addresses the forensic analysis of an encrypted drive with trim enabled.

**Comment by duckartes** [comment]
Interesting. Appreciate the heads up. Something I did not take into consideration.
