### ISSUE TITLE
Error on non-UEFI disks & a solution (GPT vs. MBR)

### ISSUE THREAD

**Issue by econo202** [nbros652/LUKS-guided-manual-partitioning#4]
The script on line 65 executes `parted $disk mktable gpt > /dev/null 2>&1`, and creates GPT partition table.

If you have a computer booting BIOS it means that you'd need a separate partition at the beginning of a disk where you'd install GRUB. Therefore after executing the stript you end up with a non-bootable system on non-UEFI computers.

The solution would be to:
- check if there is EFI partition (this is already done in lines 55-57)
- if there's EFI partition proceed as usual
- if there's no EFI partition, assume that this is a non-UEFI case, so instead of `parted $disk mktable gpt > /dev/null 2>&1` (line 65) execute `parted $disk mktable msdos > /dev/null 2>&1`

**Comment by nbros652** [comment]
You're right! This started as a script that I was building for my own system images, and I didn't need to worry about it at the time. I've been a bit busy with work of late and probably won't see a whole lot of free time before July. I'll try to fix this when I can!

**Comment by econo202** [comment]
Thank you! I'd resolve it by myself, but I don't have bash skills.

**Comment by nbros652** [comment]
This should be fixed now.
